{% set name = "sacroml" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f4edf96f22fb29bffb3d55ad856be472d35d6b18626b5b4301804e723cda78e

build:
  number: 0
  noarch: python
  entry_points:
    - sacroml = sacroml.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python {{ python_min }}
    - setuptools
    - pip
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - acro ==0.4.8
    - fpdf
    - pypdf
    - dictdiffer
    - multiprocess
    - xgboost
    - scikit-learn >=1.0,<2.0

test:
  imports:
    - sacroml
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AI-SDC/SACRO-ML
  summary: Tools for the statistical disclosure control of machine learning models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpreen
